import Foundation
import SwiftUI
import Combine

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    
    @Published var currentLanguage: String {
        didSet {
            UserDefaults.standard.set(currentLanguage, forKey: "app_language")
        }
    }
    
    init() {
        self.currentLanguage = UserDefaults.standard.string(forKey: "app_language") ?? "en"
    }
    
    func localizedString(_ key: String) -> String {
        let translations: [String: [String: String]] = [
            // Navigation & Common
            "select_community": ["en": "Select a Community", "zh": "选择社区"],
            "cancel": ["en": "Cancel", "zh": "取消"],
            "done": ["en": "Done", "zh": "完成"],
            "save": ["en": "Save", "zh": "保存"],
            
            // Login View
            "login": ["en": "Login", "zh": "登录"],
            "select_site": ["en": "Select Site", "zh": "选择站点"],
            "site": ["en": "Site", "zh": "站点"],
            "credentials": ["en": "Credentials", "zh": "凭证"],
            "username": ["en": "Username", "zh": "用户名"],
            "password": ["en": "Password", "zh": "密码"],
            "save_credentials": ["en": "Save Credentials", "zh": "保存凭证"],
            "credentials_saved": ["en": "Credentials saved successfully!", "zh": "凭证保存成功！"],
            "note": ["en": "Note", "zh": "注意"],
            "credentials_note": ["en": "Credentials are stored locally on your device. They will be used to access member-only content on the selected forum.", "zh": "凭证存储在您的设备上。它们将用于访问所选论坛的会员专属内容。"],
            
            // Settings View
            "settings": ["en": "Settings", "zh": "设置"],
            "gemini_api_key": ["en": "Gemini API Key", "zh": "Gemini API 密钥"],
            "enter_api_key": ["en": "Enter API Key", "zh": "输入 API 密钥"],
            "api_key_note": ["en": "Get your API key from Google AI Studio", "zh": "从 Google AI Studio 获取您的 API 密钥"],
            
            // AI Summary
            "ai_assistant": ["en": "AI Assistant", "zh": "AI 助手"],
            "gemini_analyzing": ["en": "Gemini is analyzing the content...", "zh": "Gemini 正在分析内容..."],
            "failed_summary": ["en": "Failed to generate summary.", "zh": "生成摘要失败。"],
            "check_api_key": ["en": "Please check your API Key in Settings.", "zh": "请在设置中检查您的 API 密钥。"],
            "try_again": ["en": "Try Again", "zh": "重试"],
            "gemini_summary": ["en": "Gemini Summary", "zh": "Gemini 摘要"],
            "cached": ["en": "Cached", "zh": "已缓存"],
            "generated_by": ["en": "Generated by Google Gemini", "zh": "由 Google Gemini 生成"],
            "regenerate": ["en": "Regenerate", "zh": "重新生成"],
            
            // Thread Detail
            "thread_reply": ["en": "Reply to thread...", "zh": "回复主题..."],
            "reply": ["en": "Reply", "zh": "答复"],
            
            // New Thread View
            "new_thread": ["en": "New Thread", "zh": "发布新主题"],
            "thread_title": ["en": "Thread Title", "zh": "主题标题"],
            "share_thoughts": ["en": "Share your thoughts...", "zh": "分享您的想法..."],
            "attachments_header": ["en": "ATTACHMENTS", "zh": "附件"],
            "add_images": ["en": "Add Images", "zh": "添加图片"],
            "thread_button": ["en": "Post", "zh": "发布"],
            "word_count": ["en": "%d words", "zh": "%d 字"],
        ]
        
        if let languageDict = translations[key],
           let translation = languageDict[currentLanguage] {
            return translation
        }
        return key // Fallback to key if translation not found
    }
    
    func localizedString(_ key: String, _ args: CVarArg...) -> String {
        let format = localizedString(key)
        return String(format: format, arguments: args)
    }
}

// Extension for convenience
extension String {
    func localized() -> String {
        return LocalizationManager.shared.localizedString(self)
    }
    
    func localized(_ args: CVarArg...) -> String {
        return LocalizationManager.shared.localizedString(self, args)
    }
}
